apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    color: blue # start with blue active
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
